openapi: 3.0.3
info:
  title: Book Service API
  description: API for managing books and their rental status
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Default server

paths:
  /:
    get:
      summary: Say Hello
      description: Returns a hello message.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string

  /books:
    get:
      summary: Get all books
      description: Retrieve a list of all books.
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookClient'

  /books/rented:
    get:
      summary: Get rented books
      description: Retrieve a list of all rented books.
      responses:
        '200':
          description: A list of rented books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookClient'

  /books/{ISBN}:
    get:
      summary: Get book by ISBN
      description: Retrieve a specific book by its ISBN.
      parameters:
        - in: path
          name: ISBN
          required: true
          schema:
            type: string
          description: ISBN of the book to retrieve
      responses:
        '200':
          description: A single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookClient'
        '404':
          description: Book not found

    put:
      summary: Update book rental status
      description: Update the rental status of a specific book by its ISBN.
      parameters:
        - in: path
          name: ISBN
          required: true
          schema:
            type: string
          description: ISBN of the book to update
        - in: query
          name: rent
          required: true
          schema:
            type: boolean
          description: New rental status (true if rented, false if available)
      responses:
        '200':
          description: Rental status updated
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Book not found

components:
  schemas:
    BookClient:
      type: object
      properties:
        ISBN:
          type: string
          description: ISBN of the book
        name:
          type: string
          description: Name of the book
        author:
          type: string
          description: Author of the book
        editor:
          type: string
          description: Publisher/editor of the book
        rented:
          type: boolean
          description: Rental status of the book (true if rented, false if available)
      required:
        - ISBN
        - name
        - author
        - rented
        - editor
