openapi: 3.0.0
info:
  title: Book Reservation API
  description: API pour la gestion des livres et des réservations de livres
  version: 1.0.0
servers:
  - url: http://localhost:8082
paths:
  /:
    get:
      summary: Dire "Bienvenue à la bibliothèque!"
      description: Renvoie un message d'accueil.
      operationId: welcomeMessage
      responses:
        '200':
          description: Succès
          content:
            text/plain:
              schema:
                type: string
                example: Bienvenue à la bibliothèque!

  /books:
    get:
      summary: Récupérer tous les livres
      description: Renvoie la liste de tous les livres disponibles dans la bibliothèque
      operationId: allBooks
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    isbn:
                      type: string
                      example: 978-3-16-148410-0
                    title:
                      type: string
                      example: Le Petit Prince
                    author:
                      type: string
                      example: Antoine de Saint-Exupéry
                    price:
                      type: number
                      format: float
                      example: 15.99
                    available:
                      type: boolean
                      example: true
                    id:
                      type: integer
                      example: 1

    post:
      summary: Ajouter un nouveau livre
      description: Ajoute un livre à la bibliothèque
      operationId: addBook
      requestBody:
        description: Détails du livre à ajouter
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isbn:
                  type: string
                  example: 978-3-16-148410-0
                title:
                  type: string
                  example: Le Petit Prince
                author:
                  type: string
                  example: Antoine de Saint-Exupéry
                price:
                  type: number
                  format: float
                  example: 15.99
                available:
                  type: boolean
                  example: true
      responses:
        '201':
          description: Livre ajouté avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Livre ajouté avec succès
                  id:
                    type: integer
                    example: 1

  /books/{isbn}:
    get:
      summary: Récupérer un livre par son ISBN
      description: Renvoie les détails d'un livre spécifique en fonction de son ISBN
      operationId: getBookByIsbn
      parameters:
        - name: isbn
          in: path
          required: true
          description: ISBN du livre
          schema:
            type: string
            example: 978-3-16-148410-0
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  isbn:
                    type: string
                    example: 978-3-16-148410-0
                  title:
                    type: string
                    example: Le Petit Prince
                  author:
                    type: string
                    example: Antoine de Saint-Exupéry
                  price:
                    type: number
                    format: float
                    example: 15.99
                  available:
                    type: boolean
                    example: true
                  id:
                    type: integer
                    example: 1
        '404':
          description: Livre non trouvé

  /books/{isbn}/reserve:
    put:
      summary: Réserver un livre
      description: Permet de réserver un livre en changeant son statut de disponibilité
      operationId: reserveBook
      parameters:
        - name: isbn
          in: path
          required: true
          description: ISBN du livre
          schema:
            type: string
            example: 978-3-16-148410-0
        - name: reserve
          in: query
          required: true
          description: Statut de la réservation (true = réservé, false = disponible)
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  Actual_Reservation:
                    type: boolean
                    example: true
        '404':
          description: Livre non trouvé

  /books/reserved:
    get:
      summary: Récupérer tous les livres réservés
      description: Renvoie la liste des livres qui sont actuellement réservés
      operationId: allReservedBooks
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    isbn:
                      type: string
                      example: 978-3-16-148410-0
                    title:
                      type: string
                      example: Le Petit Prince
                    author:
                      type: string
                      example: Antoine de Saint-Exupéry
                    price:
                      type: number
                      format: float
                      example: 15.99
                    available:
                      type: boolean
                      example: false
                    id:
                      type: integer
                      example: 1
